// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgencyServer.Models;

#nullable disable

namespace TravelAgencyServer.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelAgencyServer.Models.Account", b =>
                {
                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mail");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Mail = "test@mail.com",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("TravelAgencyServer.Models.Destination", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Country");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Country = "Morocco",
                            Price = 1000f
                        },
                        new
                        {
                            Country = "Romania",
                            Price = 1000f
                        },
                        new
                        {
                            Country = "Seychelles Island",
                            Price = 1000f
                        },
                        new
                        {
                            Country = "Turkey",
                            Price = 1000f
                        },
                        new
                        {
                            Country = "Maldives",
                            Price = 1000f
                        },
                        new
                        {
                            Country = "France",
                            Price = 1000f
                        },
                        new
                        {
                            Country = "Italy",
                            Price = 1000f
                        },
                        new
                        {
                            Country = "Egypt",
                            Price = 1000f
                        });
                });

            modelBuilder.Entity("TravelAgencyServer.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Mail");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TravelAgencyServer.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservationId");

                    b.HasIndex("Country");

                    b.HasIndex("Mail");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TravelAgencyServer.Models.Question", b =>
                {
                    b.HasOne("TravelAgencyServer.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Mail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TravelAgencyServer.Models.Reservation", b =>
                {
                    b.HasOne("TravelAgencyServer.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("Country")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgencyServer.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Mail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Destination");
                });
#pragma warning restore 612, 618
        }
    }
}
